#!/usr/bin/env node
/* copy-web.js -- stage the game into www/ for Capacitor.
 *
 * The game has no build step and never will: index.html loads twelve plain
 * <script> tags. Capacitor just needs them under a single `webDir`, so this
 * copies them verbatim. Nothing is transformed, minified or rewritten -- the
 * bytes in www/ are identical to the bytes in the repo root.
 *
 * www/ is generated and gitignored. Never edit it; edit the repo root and
 * re-run `npm run copy:web`.
 *
 * Zero dependencies (node:fs only).
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'www');

// Everything the standalone page needs, and nothing else.
const FILES = ['index.html'];
const DIRS = ['css', 'js'];

function rmrf(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyDir(src, dst);
    } else if (entry.isFile()) {
      fs.copyFileSync(src, dst);
    }
  }
}

function main() {
  rmrf(OUT);
  fs.mkdirSync(OUT, { recursive: true });

  const copied = [];

  for (const file of FILES) {
    const src = path.join(ROOT, file);
    if (!fs.existsSync(src)) {
      console.error(`copy-web: missing required file ${file}`);
      process.exit(1);
    }
    fs.copyFileSync(src, path.join(OUT, file));
    copied.push(file);
  }

  for (const dir of DIRS) {
    const src = path.join(ROOT, dir);
    if (!fs.existsSync(src)) {
      console.error(`copy-web: missing required directory ${dir}/`);
      process.exit(1);
    }
    copyDir(src, path.join(OUT, dir));
    const n = fs.readdirSync(path.join(OUT, dir)).length;
    copied.push(`${dir}/ (${n} files)`);
  }

  // A generated directory should say so.
  fs.writeFileSync(
    path.join(OUT, 'README.txt'),
    'Generated by scripts/copy-web.js. Do not edit; edit the repo root and\n' +
      'run `npm run copy:web`. This directory is gitignored.\n'
  );

  console.log(`copy-web: staged ${copied.join(', ')} -> www/`);
}

main();
